### ISSUE TITLE
Aug 7th sess

### ISSUE THREAD

**Issue by zeref221** [Bioengineering-Club-2021A/Executive-Team#1]
#test

**Comment by manaswiproject** [comment]
@Shreeya-Kadam @naman-hora @Rahul-Shah12 @nayanavarghese11 This is a test

**Comment by manaswiproject** [comment]
Comment if you've recieved a mail due to your mention in the comment

**Comment by nayanavarghese11** [comment]
> Comment if you've recieved a mail due to your mention in the comment

Got it!

**Comment by naman-hora** [comment]
test comment

**Comment by shrabanagupta** [comment]
test

**Comment by manaswiproject** [comment]
@nayanavarghese11 @zeref221 @naman-hora @Rahul-Shah12 @unorthodox19112001 @KavishaShroff02 @Debkalyan44 @anuushkajoshi @Asteriskbruh @tanishqua27 @vinita08 @shrabanagupta @mayankgandhi1307 @Samruddhi-123 @007divy @iris-byte @shraddhashinde02 

Everyone pls try and change project. Move this issue around. 
eg: 'To do' to 'in progress' to 'review in progress'

Try to change the label
eg: Remove 'new task'  and put 'in progress'

Also try to mention people:
eg: @zeref221

**Comment by manaswiproject** [comment]
If you have doubts, comment here

**Comment by iris-byte** [comment]
Got It! @manaswiproject

**Comment by manaswiproject** [comment]
**FROM NOW ON, ALL TASKS RELATED TO SESSION 1 WILL BE PUT IN THE PROJECT "Session 1"**

Click on settings, next to "Projects" (top right corner) and select "session1"
