### ISSUE TITLE
Photography team+ Creative

### ISSUE THREAD

**Issue by KavishaShroff02** [Bioengineering-Club-2021A/Executive-Team#10]
- [ ]  introductory video
- [x] #14

**Comment by unorthodox19112001** [comment]
https://drive.google.com/file/d/1uUXPG_HrswacgqQ3OfRg9-Mx7k4wz3YS/view?usp=sharing
Event video

**Comment by manaswiproject** [comment]
There is a separare issue for Hands up video. Post final video link there
