### ISSUE TITLE
Science and Marvel Topics

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#11]
Already given topics: 
1. Captain America experiment- ethical or not?                                                                                                                                   2. Was Thanos right?                                                                    
3. Use of science in war -> bio weapons (Ironman)                     
4. Time travel- possible or not (Doc Strange)                                                    
5. Will AI give rise to Ultron vs Vision
6. Doctor Octavius was onto something, he wanted to create a perfect energy system,in  which humanity would be able to sustain. Suggest ways to make doc Oc idea better
7. Jarvis should be commercialised, yes or no?                                        
8. Is Age of Ultron the future?                                                      
9. Hulk, Wakanda
10. Cross specie experimentation should be conducted or not... if so then on what basis? (Spidey and his villains)

Pls add more topics by **Thursday 10am**

**Comment by 007divy** [comment]
Moderators:

- Neilay
- Divy
- Naman
- Arya
- Anushka Joshi

Host

- Poorna

**Comment by Shreeya-Kadam** [comment]
> Moderators:
> 
> * Neilay
> * Divy
> * Naman
> * Arya
> * Anushka Joshi
> 
> Host
> 
> * Poorna

we need the characters they would like to represent so creative team can make a virtual bg

**Comment by zeref221** [comment]
- Can there ever be spiderman in real life?

(There are anatomical differences in spider and Peter Parker, which makes existence of spiderman impossible. Discuss how and why you would try to make spiderman into reality)

- Venom and Carnage are extraterrestrial microorganisms, discuss possibilities about this happening in real life and the course of action that can be taken in events of this happening
(Possible solution: Another pandemic?)


- How to kill Deadpool and Wolverine in a normal way
(Without magic, mutant powers, a multi universe earth crash or even disintegrating every last cell)

**Comment by manaswiproject** [comment]
**FINAL TOPICS:**

1. Was Thanos right?
2. Will AI give rise to Ultron vs Vision
3. Cross specie experimentation should be conducted or not... if so then on what basis? (Spidey and his villains)
4. Venom and Carnage are extraterrestrial microorganisms, discuss possibilities about this happening in real life and the course of action that can be taken in events of this happening

**Comment by manaswiproject** [comment]
Host- Poorna, Debkalyan(R)

1. Naman(M), Poorna (R), Shrabana(D)
2. Anushka J(M), Debkalyan(R), Amala(D)
3. Arya(M), Kavisha(R), Aditiy(D)
4. Neilay(M), Aditya(R), Priya(D)

Trivia- Anushka S, Debkalyan(R)

**Comment by manaswiproject** [comment]
1. Was Thanos right? Is there any other way to achieve this "perfect balance"?
2. Will AI give rise to Ultron vs Vision?
3. Scientific possibilities and consequences of cross species experimentation in the Sinister 6.
3. Cross specie experimentation should be conducted or not... if so then on what basis? (Spidey and his villains)
4. Venom and Carnage are extraterrestrial microorganisms. Discuss the possibility of this happening in real life and the course of action that can be taken in the event of this happening.
