### ISSUE TITLE
PR message for Holistic event 2- Science and Marvel 

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#12]
Pls give all updates here

**Comment by manaswiproject** [comment]
PR team pls send the PR message with form link here

**Comment by Anushka-CC-DS** [comment]
Avengers Assemble!
Join us for a group discussion this Saturday on 28th August,2021 where we discuss everything from science and experiments to unsolved superhero mysteries and their mind boggling creations.
As Captain America once very wisely said,"Whatever it takes."
Join in this Saturday and come be a part of our own little Marvel universe!

**Comment by Anushka-CC-DS** [comment]
Let me know if it requires any changes

**Comment by manaswiproject** [comment]
Doubtful on whether we should write "Avengers Assemble" cause technically its just a small part of Marvel, not the whole thing. Will leave it up to others to decide if to keep it or change it. Not a big deal

"As Captain America once very wisely said,"Whatever it takes." - what are we trying to imply here? Whatever it takes for what?

**Other than that, its crisp and to the point. Love it!**

**Comment by zeref221** [comment]
If we can use another quote instead of Captain America wala then it would be great. 
Avengers assemble is fine ig, it would capture attention as its starting of the message.
Rest all is nicely written!

**Comment by zeref221** [comment]
Can we use some key words like marvel has 
**What if Wednesday's**

So maybe we can have **Suppose Saturday's**

**Comment by 007divy** [comment]
> Avengers Assemble!
> Join us for a group discussion this Saturday on 28th August,2021 where we discuss everything from science and experiments to unsolved superhero mysteries and their mind boggling creations.
> As Captain America once very wisely said,"Whatever it takes."
> Join in this Saturday and come be a part of our own little Marvel universe!

Can we change "Join us..." from the start?....cause we don't need "join in/join us" two times in a single msg.

**Comment by Sanyogita22** [comment]
https://docs.google.com/forms/d/e/1FAIpQLScpu1QoUhRVZcG2zy7dF45_sCosRcfrX9YDaBef6rkaYTPHgA/viewform?usp=sf_link
registration form

**Comment by tanishqua27** [comment]
https://docs.google.com/forms/d/e/1FAIpQLScpu1QoUhRVZcG2zy7dF45_sCosRcfrX9YDaBef6rkaYTPHgA/viewform?usp=sf_link
Edited registration form

**Comment by manaswiproject** [comment]
Bioengineers, Assemble!

"There was an idea to bring together a group of remarkable people, to see if we could become something more"

Join us for a group discussion this Saturday on 28th August, where we brainstorm everything from science and experiments to unsolved superhero mysteries and their real world implications.

Stay tuned for the Post Credit ;)

Register to participate:
https://forms.gle/6jbnkcPDGWU3b5848

Join us this Saturday and don't forget to master your superhero landing!
