### ISSUE TITLE
Poster for Science and Marvel event 

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#13]
Pls give all updates here

**Comment by vinita08** [comment]
Suggestions are welcomed! Also please send details of the event.
![marvel poster](https://user-images.githubusercontent.com/88326489/130746624-6722921e-54db-4e04-b93e-1265b83c6857.png)

**Comment by manaswiproject** [comment]
Few changes: 
1. Change font for "science in"
2. Make J capital in "join"
3. Picture for MCU is very blurry. Maybe we can get a better one? Without the black box?
4. Picture for BEC also has Black box around it. That should preferably be removed too 
5. Align the whole "BEC X MCU." Its not in the center

**Other than all this, great job!**

**Comment by vinita08** [comment]
virtual backgrounds for moderators 
![virtual background for moderators](https://user-images.githubusercontent.com/88326489/130749009-5ec4563f-8207-44f6-989d-f6240651a0c2.png)
![virtual background for moderators (1)](https://user-images.githubusercontent.com/88326489/130749293-a236d7fc-b85d-48bf-a85a-4ea9d33d639c.png)
![virtual background for moderators (3)](https://user-images.githubusercontent.com/88326489/130749337-d66e578a-9d41-4f8f-a52c-9a2ce426ddab.png)

**Comment by vinita08** [comment]
> Few changes:
> 
> 1. Change font for "science in"
> 2. Make J capital in "join"
> 3. Picture for MCU is very blurry. Maybe we can get a better one? Without the black box?
> 4. Picture for BEC also has Black box around it. That should preferably be removed too
> 5. Align the whole "BEC X MCU." Its not in the center
> 
> **Other than all this, great job!**

1. should i keep same font as "marvel"? or try some other font?
3. Ill try to find a better pic but not sure whether ill get without the black box

**Comment by 007divy** [comment]
> virtual backgrounds for moderators
> ![virtual background for moderators](https://user-images.githubusercontent.com/88326489/130749009-5ec4563f-8207-44f6-989d-f6240651a0c2.png)
> ![virtual background for moderators (1)](https://user-images.githubusercontent.com/88326489/130749293-a236d7fc-b85d-48bf-a85a-4ea9d33d639c.png)
> ![virtual background for moderators (3)](https://user-images.githubusercontent.com/88326489/130749337-d66e578a-9d41-4f8f-a52c-9a2ce426ddab.png)

Can you also make backgrounds for Loki, Hulk, Dr. Strange, something related to Jarvis too!

**Comment by vinita08** [comment]
> > virtual backgrounds for moderators
> > ![virtual background for moderators](https://user-images.githubusercontent.com/88326489/130749009-5ec4563f-8207-44f6-989d-f6240651a0c2.png)
> > ![virtual background for moderators (1)](https://user-images.githubusercontent.com/88326489/130749293-a236d7fc-b85d-48bf-a85a-4ea9d33d639c.png)
> > ![virtual background for moderators (3)](https://user-images.githubusercontent.com/88326489/130749337-d66e578a-9d41-4f8f-a52c-9a2ce426ddab.png)
> 
> Can you also make backgrounds for Loki, Hulk, Dr. Strange, something related to Jarvis too!

Yes for that please let me know how many members are taking part for moderators with what roles.

**Comment by manaswiproject** [comment]
> > Few changes:
> > 
> > 1. Change font for "science in"
> > 2. Make J capital in "join"
> > 3. Picture for MCU is very blurry. Maybe we can get a better one? Without the black box?
> > 4. Picture for BEC also has Black box around it. That should preferably be removed too
> > 5. Align the whole "BEC X MCU." Its not in the center
> > 
> > **Other than all this, great job!**
> 
> 1. should i keep same font as "marvel"? or try some other font?
> 2. Ill try to find a better pic but not sure whether ill get without the black box

@vinita08 
1. Same font as "MARVEL" will do
2. I'll try to find one without the box too. I'll upload here if i find it

**Comment by 007divy** [comment]
> > > virtual backgrounds for moderators
> > > ![virtual background for moderators](https://user-images.githubusercontent.com/88326489/130749009-5ec4563f-8207-44f6-989d-f6240651a0c2.png)
> > > ![virtual background for moderators (1)](https://user-images.githubusercontent.com/88326489/130749293-a236d7fc-b85d-48bf-a85a-4ea9d33d639c.png)
> > > ![virtual background for moderators (3)](https://user-images.githubusercontent.com/88326489/130749337-d66e578a-9d41-4f8f-a52c-9a2ce426ddab.png)
> > 
> > 
> > Can you also make backgrounds for Loki, Hulk, Dr. Strange, something related to Jarvis too!
> 
> Yes for that please let me know how many members are taking part for moderators with what roles.

For now, we need BG for Captain America, Ironman, Spiderman, Loki, Hulk, DR. Strange and also one Avenger base for all other team members.

**Comment by manaswiproject** [comment]
![Marvel](https://user-images.githubusercontent.com/81001658/130756731-41367473-d84f-4095-9393-3c5fea631af9.png)
![Marvel 2](https://user-images.githubusercontent.com/81001658/130756741-bc000904-5d47-40c4-92bc-7023ad69be26.png)

**Comment by manaswiproject** [comment]
These should work

**Comment by Shreeya-Kadam** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.behance.net%2Fsearch%2Fprojects%2F%3Fsearch%3Dmarvel-cinematic-universe&psig=AOvVaw1PF61eNZWKkoQYFVBJ2fva&ust=1629966837334000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPCr0OXhy_ICFQAAAAAdAAAAABAD
@vinita08 check out this link

**Comment by Shreeya-Kadam** [comment]
![marvel](https://user-images.githubusercontent.com/80977532/130757298-a3503004-1f28-41a4-a34d-57cc18a27276.png)


Check this one @vinita08

**Comment by 007divy** [comment]
Check this out!1
Aagam made this
![WhatsApp Image 2021-08-25 at 2 06 20 PM](https://user-images.githubusercontent.com/80999835/130758432-f120c0f3-a029-4bdc-b7e6-3de7b0af72f2.jpeg)

**Comment by Shreeya-Kadam** [comment]
![marvel-removebg-preview](https://user-images.githubusercontent.com/80977532/130758645-5b7de75b-1827-4257-921d-e8838160d951.png)

Without background

**Comment by Shreeya-Kadam** [comment]
![Uploading marvel poster.png…]()

This is the updated poster.

**Comment by Shreeya-Kadam** [comment]
![marvel poster](https://user-images.githubusercontent.com/80977532/130762190-eaa71ca1-5add-45ae-8213-8cf5c7a73298.png)

This is the updated poster.

**Comment by vinita08** [comment]
loki, dr. strange, hulk, common 
![virtual background for moderators (9)](https://user-images.githubusercontent.com/88326489/130765426-07fe52aa-2dbb-4dd6-b186-bba9da734860.png)
![virtual background for moderators (8)](https://user-images.githubusercontent.com/88326489/130765431-ed16ae79-dd5c-4427-a1cc-ae3172f58c78.png)
![virtual background for moderators (7)](https://user-images.githubusercontent.com/88326489/130765446-c6930a73-9aaa-43c0-bf52-b2c6605b2e48.png)
![virtual background for moderators (6)](https://user-images.githubusercontent.com/88326489/130765522-ad89364a-6f84-41c0-8df8-4a145e8c8b71.png)
![virtual background for moderators (5)](https://user-images.githubusercontent.com/88326489/130765601-8e1187e1-5670-4398-b597-3b137bc46e5b.png)
![virtual background for moderators (4)](https://user-images.githubusercontent.com/88326489/130765640-451eeb7b-7206-46f6-9782-c6a3b93be71b.png)

**Comment by vinita08** [comment]
![virtual background for moderators (8)](https://user-images.githubusercontent.com/88326489/130770294-eaea2579-8b6a-4dd0-9c90-6e88fd2ccc93.png)
![virtual background for moderators (7)](https://user-images.githubusercontent.com/88326489/130770313-b40c0959-e0da-4580-8a82-8e0f5b2205fb.png)
![virtual background for moderators (9)](https://user-images.githubusercontent.com/88326489/130770493-a68bb665-0f0a-48b6-9636-1e69568da7e9.png)
all the virtual backgrounds (i flipped them cause meeting mai fir sidha dikhega)
![virtual background for moderators (3)](https://user-images.githubusercontent.com/88326489/130770101-524db107-6c78-46ec-bf24-b3c5b7d4f0ce.png)
![virtual background for moderators (4)](https://user-images.githubusercontent.com/88326489/130770121-e64cfd14-dbe9-40f8-87f6-562b5df286f5.png)
![virtual background for moderators (5)](https://user-images.githubusercontent.com/88326489/130770132-b8befd40-2ef5-45e7-ba99-6c98a0e98a73.png)
![virtual background for moderators (6)](https://user-images.githubusercontent.com/88326489/130770138-e8922253-1c43-4aff-a9b7-82647bc7ff7b.png)
![virtual background for moderators (2)](https://user-images.githubusercontent.com/88326489/130770143-6abf3234-21a5-46d8-8e68-ae60a617192e.png)
![virtual background for moderators (1)](https://user-images.githubusercontent.com/88326489/130770167-a09a9bd1-7398-43e0-8627-bbadc6cdc6ba.png)
![virtual background for moderators](https://user-images.githubusercontent.com/88326489/130770186-797f7b59-c58b-4285-848e-f49a94de43ca.png)
![virtual background for moderators (10)](https://user-images.githubusercontent.com/88326489/130770757-2fb304bd-7c94-4b51-b198-b26b4c20ac80.png)

**Comment by nayanavarghese11** [comment]
[Uploading Marvel Pos.zip…]()

**Comment by nayanavarghese11** [comment]
![1](https://user-images.githubusercontent.com/68808399/130771382-10a9bbfe-1cb8-413c-9a3b-75ddb8370a9f.png)
![2](https://user-images.githubusercontent.com/68808399/130771387-7767f8f1-ca17-46dc-a391-08aefc5c5121.png)
![3](https://user-images.githubusercontent.com/68808399/130771390-bb49f5eb-974a-4691-b487-d583586b8da3.png)
![4](https://user-images.githubusercontent.com/68808399/130771395-565454cc-664d-41b8-9eec-0e8c1c5e8e1e.png)
![5](https://user-images.githubusercontent.com/68808399/130771398-1c34c2b9-75af-4c2b-8f6b-903818dea970.png)
![6](https://user-images.githubusercontent.com/68808399/130771403-d95ecacc-67d0-494c-a6d3-09a76e351614.png)
![7](https://user-images.githubusercontent.com/68808399/130771406-cd600210-468d-4aaf-a5af-78a739c1e854.png)

**Comment by aagambamb** [comment]
Aagam here aded some quotes of super heroes

![WhatsApp Image 2021-08-25 at 4 00 36 PM](https://user-images.githubusercontent.com/80999835/130776689-55d2b045-0a9a-4e24-a3f8-376510b80681.jpeg)

**Comment by manaswiproject** [comment]
@nayanavarghese11 Pls work on Poster no 3. Specification will be told by @Shreeya-Kadam

**Comment by nayanavarghese11** [comment]
Poster 3: Updated

![Marvel Pos](https://user-images.githubusercontent.com/68808399/130903217-fd533cf8-5bba-4e0d-8caa-f7924a37ffe4.png)

**Comment by nayanavarghese11** [comment]
![Marvel Pos (1)](https://user-images.githubusercontent.com/68808399/130903574-f10c7988-a759-4379-9452-cc71e950e2e5.png)

**Comment by nayanavarghese11** [comment]
The character portion in the above poster is a little blur, so if someone gets a clearer pic please send it.

**Comment by nayanavarghese11** [comment]
![9](https://user-images.githubusercontent.com/68808399/130911740-d2d24ed8-8375-47e6-ada5-f8e24f6a0c1a.png)

**Comment by nayanavarghese11** [comment]
Few more sample posters.

![10](https://user-images.githubusercontent.com/68808399/130911773-a8b100fc-8e67-486e-a06b-53b4b76833bd.png)

**Comment by nayanavarghese11** [comment]
![11](https://user-images.githubusercontent.com/68808399/130911846-23cd5af7-60c5-4a7a-91a9-b88b30d8f075.png)

**Comment by nayanavarghese11** [comment]
![12](https://user-images.githubusercontent.com/68808399/130911916-58f24310-20ab-4e4f-a738-42fadf221d0a.png)

**Comment by unorthodox19112001** [comment]
@nayanavarghese11 Could you please join the letters of BEC just like MARVEL?

**Comment by 007divy** [comment]
@vinita08  Is it possible to remove the white bg of the logo?

**Comment by vinita08** [comment]
![marvel poster (2)](https://user-images.githubusercontent.com/88326489/130936465-b96fb17e-d260-4fb7-9102-d467bec1a640.png)

**Comment by nayanavarghese11** [comment]
> @nayanavarghese11 Could you please join the letters of BEC just like MARVEL?

![Marvel Pos (2)](https://user-images.githubusercontent.com/68808399/130941989-a7c99bf0-f5da-4a90-a590-e859ce6cbaea.png)

**Comment by nayanavarghese11** [comment]
![13](https://user-images.githubusercontent.com/68808399/130947844-203da489-24e7-4dd4-b7e5-a4bfda36f64b.png)

**Comment by nayanavarghese11** [comment]
![14](https://user-images.githubusercontent.com/68808399/130947907-e4f32239-7496-425e-a007-179efa1ff92f.png)
