### ISSUE TITLE
Hands Up Event video

### ISSUE THREAD

**Issue by a24s** [Bioengineering-Club-2021A/Executive-Team#14]

**Comment by manaswiproject** [comment]
Final video link- https://drive.google.com/file/d/1uUXPG_HrswacgqQ3OfRg9-Mx7k4wz3YS/view?usp=sharing

**Comment by manaswiproject** [comment]
We have a few suggestions about the video background music. We'll discuss them in the meeting today. The issue isn't closed yet

**Comment by manaswiproject** [comment]
https://drive.google.com/file/d/1sO9kruXCQxzNxfZUPcZU3T5rNMJDEbQu/view?usp=sharing
