### ISSUE TITLE
PR message for meme competition

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#16]
Kindly give all updates here

**Comment by Samruddhi-123** [comment]
**Career Event**
BIOENGINEERING CLUB

(5mins)
Anchors- Prajakta, Tanvi(2mins)

BioNews- Arohi, Girish(5 mins)
(2mins)

Project- We are looking into it.

Internship Experience(10mins)
(2mins)

Startup Story
(2mins)

Guest Speaker-(25 mins)
Vote of thanks (2mins)[Ask Preetam sir]

**Comment by Sanyogita22** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSeBLrJXQlq3k_cWL6Sj2lwv9K8VyFatas6G8YAzeuxueizFow/viewform?usp=sf_link


https://sanyudhakane5.surveysparrow.com/s/Event-3--LORD-OF-MEMES/tt-faa0b055ad

**Comment by Anushka-CC-DS** [comment]
Brace yourselves,the meme war is here!
The Bioengineering Club has planned a *drumroll please* a Meme War.
Get your meme faces on as Meme lords battle out their best memes on Saturday, _ September.
Show us what you got and send in your submissions by _ September.
Your memes should be related to our domain and should be original,and we'll see you all on Saturday.
May the best meme win!

**Comment by Anushka-CC-DS** [comment]
Let me know if it requires any changes!

**Comment by shrabanagupta** [comment]
> Brace yourselves,the meme war is here!
> The Bioengineering Club has planned a _drumroll please_ a Meme War.
> Get your meme faces on as Meme lords battle out their best memes on Saturday, _ September.
> Show us what you got and send in your submissions by _ September.
> Your memes should be related to our domain and should be original,and we'll see you all on Saturday.
> May the best meme win!

could we just mention that "our domain" here means related to bioengineering?

**Comment by manaswiproject** [comment]
MEMES WANTED! MIT BEC is looking for the **freshest quality of memes** (change to something better) and we are asking you, our funniest students, to provide them for us in our newest event: Lord Of The Memes
Show us what you got and send in your submissions by, Thursday 9th September.
Your memes must be original and could be related to anything bioengineering. 
Multiple entries are allowed
Do you think you have it in you to become the Lord of the memes? \

*Maybe something like this?*
*Feel free to make changes*

**Comment by iris-byte** [comment]
> Brace yourselves,the meme war is here!
> The Bioengineering Club has planned a _drumroll please_ a Meme War.
> Get your meme faces on as Meme lords battle out their best memes on Saturday, _ September.
> Show us what you got and send in your submissions by _ September.
> Your memes should be related to our domain and should be original,and we'll see you all on Saturday.
> May the best meme win!

Suggestion: 
Brace yourselves and stand a chance to be entitled as The Lord Of Memes!
The Bioengineering Club has planned, _drumroll please_, a Meme War.
Get your meme faces on as Meme lords battle out their best memes on Saturday, _ September.
Show us what you got and send in your submissions by _ September.
Your memes should be related to our domain and should be original. 
May the best meme win!

**Comment by Sanyogita22** [comment]
> MEMES WANTED! MIT BEC is looking for the **freshest quality of memes** (change to something better) and we are asking you, our funniest students, to provide them for us in our newest event: Lord Of The Memes
> Show us what you got and send in your submissions by, Thursday 9th September.
> Your memes must be original and could be realted to anything bioengineering.
> Multiple entries are allowed
> Do you think you have it in you to become the Lord of the memes? \
> 
> _Maybe something like this?_
> _Feel free to make changes_

can we keep it just one attempt

**Comment by manaswiproject** [comment]
> https://docs.google.com/forms/d/e/1FAIpQLSeBLrJXQlq3k_cWL6Sj2lwv9K8VyFatas6G8YAzeuxueizFow/viewform?usp=sf_link
> 
> https://sanyudhakane5.surveysparrow.com/s/Event-3--LORD-OF-MEMES/tt-faa0b055ad

@Sanyogita22 
This form looks great! Just a few small changes:

1. Pls change the the title to "Lord of **the** memes"
2. Change "Your good name" to "Name"
3. Remove the mood smileys at the end
4. Change rule 2 to: "The meme photo should be in .jpg or .jpeg format with a file size not above 10 MB"
5. Add space betrween rule 3 and 4
6. In Judging criteria change line no 3 to : "Relevance: How relevant your meme is with respect to the theme given to you (i.e. Bioengineering)"
7. In Judging criteria change line 6 to: "How innovatively you use your meme template!"
8. Remove the sentence "The decision of the judges will be final and binding."

**Comment by manaswiproject** [comment]
> > MEMES WANTED! MIT BEC is looking for the **freshest quality of memes** (change to something better) and we are asking you, our funniest students, to provide them for us in our newest event: The Lord Of The Memes
> > Show us what you got and send in your submissions by, Thursday 9th September.
> > Your memes must be original and could be realted to anything bioengineering.
> > Multiple entries are allowed
> > Do you think you have it in you to become the Lord of the memes? \
> > _Maybe something like this?_
> > _Feel free to make changes_
> 
> can we keep it just one attempt

As in, you want to keep just one entry per participant?
We actually wanted to allow multiple entries so people can have a little fun with it and so that we get more submissions. Also, so that the winners feel like they won from a big pool of participants XD

**Comment by Sanyogita22** [comment]
> > https://docs.google.com/forms/d/e/1FAIpQLSeBLrJXQlq3k_cWL6Sj2lwv9K8VyFatas6G8YAzeuxueizFow/viewform?usp=sf_link
> > https://sanyudhakane5.surveysparrow.com/s/Event-3--LORD-OF-MEMES/tt-faa0b055ad
> 
> @Sanyogita22
> This form looks great! Just a few small changes:
> 
> 1. Pls change the the title to "Lord of **the** memes"
> 2. Change "Your good name" to "Name"
> 3. Remove the mood smileys at the end
> 4. Change rule 2 to: "The meme photo should be in .jpg or .jpeg format with a file size not above 10 MB"
> 5. Add space betrween rule 3 and 4
> 6. In Judging criteria change line no 3 to : "Relevance: How relevant your meme is with respect to the theme given to you (i.e. Bioengineering)"
> 7. In Judging criteria change line 6 to: "How innovatively you use your meme template!"
> 8. Remove the sentence "The decision of the judges will be final and binding."

yuppp i'll do it

**Comment by Sanyogita22** [comment]
> > > MEMES WANTED! MIT BEC is looking for the **freshest quality of memes** (change to something better) and we are asking you, our funniest students, to provide them for us in our newest event: The Lord Of The Memes
> > > Show us what you got and send in your submissions by, Thursday 9th September.
> > > Your memes must be original and could be realted to anything bioengineering.
> > > Multiple entries are allowed
> > > Do you think you have it in you to become the Lord of the memes? 
> > > _Maybe something like this?_
> > > _Feel free to make changes_
> > 
> > 
> > can we keep it just one attempt
> 
> As in, you want to keep just one entry per participant?
> We actually wanted to allow multiple entries so people can have a little fun with it and so that we get more submissions. Also, so that the winners feel like they won from a big pool of participants XD

so in that case what i'll do is keep 3 or 5 upload slides
is that okay?

**Comment by manaswiproject** [comment]
> > > > MEMES WANTED! MIT BEC is looking for the **freshest quality of memes** (change to something better) and we are asking you, our funniest students, to provide them for us in our newest event: The Lord Of The Memes
> > > > Show us what you got and send in your submissions by, Thursday 9th September.
> > > > Your memes must be original and could be realted to anything bioengineering.
> > > > Multiple entries are allowed
> > > > Do you think you have it in you to become the Lord of the memes?
> > > > _Maybe something like this?_
> > > > _Feel free to make changes_
> > > 
> > > 
> > > can we keep it just one attempt
> > 
> > 
> > As in, you want to keep just one entry per participant?
> > We actually wanted to allow multiple entries so people can have a little fun with it and so that we get more submissions. Also, so that the winners feel like they won from a big pool of participants XD
> 
> so in that case what i'll do is keep 3 or 5 upload slides
> is that okay?

Perfect! That works!

**Comment by Sanyogita22** [comment]
can u please tell me the exact time of submission

**Comment by manaswiproject** [comment]
That'd be, Thursday 9th Aug by 6pm

**Comment by Sanyogita22** [comment]
> That'd be, Thursday 9th Aug by 6pm

today starting from 10 pm to 9th sept 6pm.....is what am adding in the fomr
okayy?

**Comment by zeref221** [comment]
Yes, go ahead with today 10pm to 9th sept 6pm!

**Comment by manaswiproject** [comment]
_**Final PR message:**_

Stand a chance to be titled "Lord Of The Memes"

The Bioengineering Club is hosting a meme-making competition this week and we are inviting you to show us how creative you can be!

Your memes should be original and related to our domain (i.e. on topics related to bioengineering) 

Send in your submissions to us by 6pm on Thursday, 9th September

Submission link:https://sprw.io/stt-faa0b055ad

May the best meme win!
