### ISSUE TITLE
Poster for Meme competition

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#17]
Kindly give up updates here

**Comment by nayanavarghese11** [comment]
Sample 
![Meme War](https://user-images.githubusercontent.com/68808399/131968868-2b4520e2-563f-435a-acec-cc32304363ac.png)

**Comment by nayanavarghese11** [comment]
![Meme War (2)](https://user-images.githubusercontent.com/68808399/131976108-8d7e5fb3-1e3a-40de-8fec-d00fef5d8b64.png)

**Comment by vinita08** [comment]
![meme poster](https://user-images.githubusercontent.com/88326489/131981927-db131cdb-53c3-4ba5-b99a-efd1e71ae6a6.png)
For Stories

**Comment by vinita08** [comment]
![meme poster (3)](https://user-images.githubusercontent.com/88326489/131985644-9cc21e74-bef1-49d6-9e79-59e7a5769519.png)

**Comment by 007divy** [comment]
> Sample
> ![Meme War](https://user-images.githubusercontent.com/68808399/131968868-2b4520e2-563f-435a-acec-cc32304363ac.png)

Left side wale pics mai, Can we use Drake waka template?

**Comment by nayanavarghese11** [comment]
![3](https://user-images.githubusercontent.com/68808399/132007844-ba69ef14-1bdc-4b34-a75b-6557c7a0a769.png)

**Comment by nayanavarghese11** [comment]
![5](https://user-images.githubusercontent.com/68808399/132007890-871f23a8-39ea-4bc5-8561-9e72af4a94da.png)

**Comment by nayanavarghese11** [comment]
![6](https://user-images.githubusercontent.com/68808399/132007944-831372f2-285e-4dd6-a8f8-3760baf4fa1f.png)

**Comment by vinita08** [comment]
![meme poster (4)](https://user-images.githubusercontent.com/88326489/132023032-b2841ce0-ac89-47aa-8c66-a898fea61fe3.png)
for stories

**Comment by Shreeya-Kadam** [comment]
> ![meme poster (4)](https://user-images.githubusercontent.com/88326489/132023032-b2841ce0-ac89-47aa-8c66-a898fea61fe3.png)
> for stories

please change 'meme contest' to 'Lord of Memes'

**Comment by vinita08** [comment]
![meme poster (5)](https://user-images.githubusercontent.com/88326489/132118006-a24f15f0-cdc7-4463-bd8a-aa4e5c0aa1b5.png)

**Comment by nayanavarghese11** [comment]
![Meme War (14)](https://user-images.githubusercontent.com/68808399/132246326-b679b7ad-575b-4417-81e8-bd050c3c22b4.png)

**Comment by nayanavarghese11** [comment]
![Meme War (13)](https://user-images.githubusercontent.com/68808399/132246363-47c6e363-3694-49e7-b37e-fd00c966b7ea.png)

**Comment by nayanavarghese11** [comment]
![Meme War (12)](https://user-images.githubusercontent.com/68808399/132246384-c81c67ad-c595-4aed-b7d0-0ce0cf60c666.png)

**Comment by nayanavarghese11** [comment]
![Meme War (11)](https://user-images.githubusercontent.com/68808399/132246431-92c770c1-1500-4bf6-a2f3-d15feefb79f2.png)

**Comment by nayanavarghese11** [comment]
![Meme War (4)](https://user-images.githubusercontent.com/68808399/132246474-ecf0308e-29de-40b5-ab97-c4435c7777b2.png)

**Comment by manaswiproject** [comment]
![Uploading WhatsApp Image 2021-09-06 at 5.37.07 PM.jpeg…]()

**Comment by manaswiproject** [comment]
FINAL POSTER

![Lord of the memes poster-final](https://user-images.githubusercontent.com/81001658/132288824-ed685eb5-f043-4fac-8741-c6d90bcc27eb.jpeg)

**Comment by nayanavarghese11** [comment]
Final Poster part 2
![Meme War Final ](https://user-images.githubusercontent.com/68808399/132289101-3702e3c7-fbeb-4e41-8752-0c4f00657f0b.png)

**Comment by manaswiproject** [comment]
> Final Poster part 2
> ![Meme War Final ](https://user-images.githubusercontent.com/68808399/132289101-3702e3c7-fbeb-4e41-8752-0c4f00657f0b.png)

Good poster. Needs improvement

**Comment by manaswiproject** [comment]
@nayanavarghese11 pls check

**Comment by manaswiproject** [comment]
> 

test
