### ISSUE TITLE
Video for Holistic Event 2: Science and Marvel

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#18]
@Asteriskbruh  Pls send final link here after you're done making the full video (for documentation)

**Comment by a24s** [comment]
Video link: https://drive.google.com/file/d/1CWAdimAlhwHPkeM_dPhh9aqDXB4ndUhB/view
(not final, under review)

**Comment by a24s** [comment]
Updated version with changes- https://drive.google.com/file/d/1Uu2e4hcH4wGcvAujLrRV7Hs_Keeoy2Dw/view
