### ISSUE TITLE
Freshers Event

### ISSUE THREAD

**Issue by 007divy** [Bioengineering-Club-2021A/Executive-Team#19]
Date - 25th September, 2021
Invite all other club/grp's people (Ask their ppts too)
Set meeting with core-core next week (8th September, 9 PM)

- introduction of the event
- their roles
- ppt (first page-logo) [before - 20th September]
- Can we make one alag ppt for sare club's logo for starting the event?

Give us the final number of ppl coming from particular club

**Comment by manaswiproject** [comment]
Panel- Prez, Secretary, Head 
Team members welcome to attend event
No audience, no faculty
Platform- Teams 
Icebreaker- Music

**Comment by manaswiproject** [comment]
IDEAS: (Anushka Joshi)
1) you can have a trailer for the club - events till now , bloopers , inside jokes 
2) some kind of theme for clothes ? everyone wears some kind of color or something (sounds a little tacky idk) 
3) as kavisha said , virtual backgrounds ??

**Comment by manaswiproject** [comment]
Poorna- Have a Quick Talent Showcase segment at the end where the freshers can show some quick talents

**Comment by tanishqua27** [comment]
"One random object" activity : Divide the participants into teams , ask a team member to pick one random object that is in their room and describe that object in a animate way to the other teams and the team which guesses maximum objects fastest ,wins .

**Comment by poornaaa** [comment]
" *Introdu-chain* "
Participant List wise every 1st-year student introduces themselves in 4 lines but with a catch - A person will introduce themself starting with the last word spoken by the preceding person's introduction.
for eg:- the last word of person A's intro is "icecream"
              then the first word of the next person's intro becomes "icecream" as well
This will make sure that the introduction of FY students is done (so they feel a little more comfortable ) while keeping it creative and not cliche

**Comment by shrabanagupta** [comment]
**Deadlines for PR message and poster:**

1. **PR message 1 (via mail)** :-  invitation + poster 
- deadline for PR team to create:  21st Sept 
- deadline for sending:  22nd Sept (5pm) 

2. **PR message 2 (via mail)** :-  confirmation + remainder + link 
- deadline for PR team to create:  21st Sept
- deadline for sending:  24th Sept  

3. **Poster with PR msg 1** 
- ready by 20th invitation poster: coordinate with other clubs for logos

4. **Background for BEC team** - ready by 22nd 
5. **Itinerary** - by 20th




 6. **Form for data collection** - Access to all clubs

**Comment by Sanyogita22** [comment]
Hey Freshers,
Welcome to MIT-BIO!
We are so excited to have you here with us!
We have an informal session planned for you,with all the clubs of SBSR to introduce ourselves and brief you about our workings and get to know each other better.
Join us on 25th @ 5:30pm and get to know your institution better!
Do join in we'll make it our responsibility to make sure you have fun.

**Comment by 007divy** [comment]
**HOST**

1.  Tanishqua (For starting the event)
2.  Anushka Singh (for Icebreaker) 

**Screen Share**

1.  Sanyogita Dhakane

**Poster**

1.  Poster no 14

**PPT**

1.  Heading - Abount us - What we do - Photos of members - Tag line

**Platform**

1.  Zoom / Microsoft

**Icebreaker**

1.  True/False 

** Contents of invitation**

-Make the msg more gen-z
- Welcoming and excited, make them feel invited. (eg. welcome kid, you're an avenger now)
- A panel of all clubs will be present
- Icebreaker session
