### ISSUE TITLE
Holistic activity ideas!

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#2]
A **virtual treasure hunt**. Bunch of "academic clues" will lead to a conclusion. Participants can make teams of x members (5>=x>=3). First team to reach end wins
 
Things to do:
1. Build a (interesting) story
2. Write (solvable) clues
3. Make rules

Time taken: Upwards of 2 hours 

#comment suggestions, changes or concerns

**Comment by zeref221** [comment]
**Introductory video ideas** _(Even if we aren't doing it, we can incorporate these ideas in some other way)_

 • Reels (An interface where we can see a person scrolling and we can see the reels where we can give introduction of our club) 

 • YouTube reaction video format ( Everybody likes rxn videos and we can even comment of stuff using this)

 • The office (show) types interview (imaginary) question video (about what the club is)

 • A kind of video where there is continuation in between the characters ( Like the reels where one person throws something and the other catches it in their own video)

 • Old bioeng club with coffin dance ( Possible meme? Check feasibility)

Goals of the video:
People should have a good understanding of what the club is about.
Everyone's individuality and quirky nature would be displayed.
Definitely shouldn't be boring as it is our first impression.
Should provide a good introduction about what the club is going to be achieving in the coming semester.

**Comment by zeref221** [comment]
**Random ideas for bioeng club**

- Rap battle btw Career and holistic
- Tacos Tuesday
- Make a pantry for our college! (Priority basis?)

**Comment by manaswiproject** [comment]
> **Introductory video ideas** _(Even if we aren't doing it, we can incorporate these ideas in some other way)_
> 
>  • Reels (An interface where we can see a person scrolling and we can see the reels where we can give introduction of our club)
> 
>  • YouTube reaction video format ( Everybody likes rxn videos and we can even comment of stuff using this)
> 
>  • The office (show) types interview (imaginary) question video (about what the club is)
> 
>  • A kind of video where there is continuation in between the characters ( Like the reels where one person throws something and the other catches it in their own video)
> 
>  • Old bioeng club with coffin dance ( Possible meme? Check feasibility)
> 
> Goals of the video:
> People should have a good understanding of what the club is about.
> Everyone's individuality and quirky nature would be displayed.
> Definitely shouldn't be boring as it is our first impression.
> Should provide a good introduction about what the club is going to be achieving in the coming semester.

**Comment by zeref221** [comment]
> A **virtual treasure hunt**. Bunch of "academic clues" will lead to a conclusion. Participants can make teams of x members (5>=x>=3). First team to reach end wins
> 
> Things to do:
> 
> 1. Build a (interesting) story
> 2. Write (solvable) clues
> 3. Make rules
> 
> Time taken: Upwards of 2 hours
> 
> #comment suggestions, changes or concerns

#test
