### ISSUE TITLE
Poster for Freshers Event 

### ISSUE THREAD

**Issue by vinita08** [Bioengineering-Club-2021A/Executive-Team#23]
Deadlines:
Poster with PR msg1- 20TH SEPT (MON)
Itinerary- 22TH SEPT(WED)
BEC virtual backgrounds - 20TH SEPT (MON)

**Comment by vinita08** [comment]
Deadlines:
Poster with PR msg1- 20TH SEPT (MON)
Itinerary- 22TH SEPT(WED)
BEC virtual backgrounds - 20TH SEPT (MON)

**Comment by vinita08** [comment]
Virtual Backgrounds
A)
![BEC TEAM](https://user-images.githubusercontent.com/88326489/133923909-235b808f-3c2b-4940-a096-d57a4642acdf.png)

**Comment by vinita08** [comment]
B)
![BEC TEAM (1)](https://user-images.githubusercontent.com/88326489/133923935-aec55380-afc6-4b8d-b183-641db4e8aff1.png)

**Comment by KavishaShroff02** [comment]
1. the guys on the DNA with the gear, look like they are bringing the gear down, instead of taking it up, we wanna show that we are lifting people up, so maybe reposition that.
2. can we have one more stick figure holding the logo, to show like it's a team effort.
3. maybe change the font, if find any better.

**Comment by iris-byte** [comment]
> B)
> ![BEC TEAM (1)](https://user-images.githubusercontent.com/88326489/133923935-aec55380-afc6-4b8d-b183-641db4e8aff1.png)

it'd be better if the colour of the original BEC logo is maintained.

**Comment by nayanavarghese11** [comment]
Poster Sample 1

![1](https://user-images.githubusercontent.com/68808399/133935023-6035a26a-8704-4c2a-a8a0-9980db4c856c.png)

**Comment by nayanavarghese11** [comment]
Poster sample 2

![2](https://user-images.githubusercontent.com/68808399/133935035-444736d1-4ff8-446f-b7a4-b1dccd8a171d.png)

**Comment by nayanavarghese11** [comment]
Poster sample 3

![3](https://user-images.githubusercontent.com/68808399/133935048-32db97ae-73a8-4501-ac0a-9aea44ad306b.png)

**Comment by nayanavarghese11** [comment]
Poster sample 4

![4](https://user-images.githubusercontent.com/68808399/133935059-baa779fd-4d9f-4a48-aa4b-2b43a2c98221.png)

**Comment by nayanavarghese11** [comment]
Poster sample 5

![5](https://user-images.githubusercontent.com/68808399/133935068-e83e4ddb-aa51-4ee1-9622-48a4a2e81a93.png)

**Comment by nayanavarghese11** [comment]
Poster sample 6

![6](https://user-images.githubusercontent.com/68808399/133935087-cce239ea-2726-4b43-bd96-61bc65e344a5.png)

**Comment by nayanavarghese11** [comment]
Poster sample 7

![7](https://user-images.githubusercontent.com/68808399/133935117-488d1a4a-b19e-49de-850d-db662163912c.png)

**Comment by nayanavarghese11** [comment]
Poster sample 8

![Uploading 11.png…]()

**Comment by nayanavarghese11** [comment]
Poster sample 8

![11](https://user-images.githubusercontent.com/68808399/133939280-8d05cce7-69b7-494c-8f2d-0b3afb18f20f.png)

**Comment by nayanavarghese11** [comment]
Poster sample 9

![9](https://user-images.githubusercontent.com/68808399/133939293-d4d23202-9041-4b35-9b36-77e71505588d.png)

**Comment by nayanavarghese11** [comment]
Poster sample 10

![7](https://user-images.githubusercontent.com/68808399/133939308-f9e0e292-6300-404b-927a-eaafb51d4d1c.png)

**Comment by nayanavarghese11** [comment]
Poster sample 11

![6](https://user-images.githubusercontent.com/68808399/133939321-227d9793-befd-4a18-80c8-47ac8180b882.png)

**Comment by nayanavarghese11** [comment]
Poster sample 12

![1](https://user-images.githubusercontent.com/68808399/133939340-ff29dd9b-d7cf-4823-b594-8a88969e87ac.png)

**Comment by KavishaShroff02** [comment]
can we call it fresher's introduction event?

**Comment by vinita08** [comment]
updated Virtual Backgrounds 
![BEC TEAM VB](https://user-images.githubusercontent.com/88326489/133970163-6334ab57-8dbb-432c-921e-b17fd9c3208a.png)

**Comment by vinita08** [comment]
![BEC TEAM VB (1)](https://user-images.githubusercontent.com/88326489/133970222-e66b3f08-27b1-4ddd-afec-1e329c6ca361.png)

**Comment by nayanavarghese11** [comment]
> can we call it fresher's introduction event?

Yes, I will do it once the poster design is confirmed.

**Comment by KavishaShroff02** [comment]
> Poster sample 8
> 
> ![11](https://user-images.githubusercontent.com/68808399/133939280-8d05cce7-69b7-494c-8f2d-0b3afb18f20f.png)

final background

**Comment by KavishaShroff02** [comment]
> Poster sample 7
> 
> ![7](https://user-images.githubusercontent.com/68808399/133935117-488d1a4a-b19e-49de-850d-db662163912c.png)

this design

**Comment by nayanavarghese11** [comment]
Sample 13
![Fresher's Event](https://user-images.githubusercontent.com/68808399/133999140-8ca0e91b-7562-4d79-8d38-d29d82c2c575.png)

**Comment by nayanavarghese11** [comment]
Sample 14

![Uploading Fresher's Event.png…]()

**Comment by nayanavarghese11** [comment]
Sample 14

![Fresher's Event (1)](https://user-images.githubusercontent.com/68808399/133999255-d7e448e5-1b81-474e-9b0a-18d29fc39974.png)

**Comment by zeref221** [comment]
> Poster sample 8
> 
> ![11](https://user-images.githubusercontent.com/68808399/133939280-8d05cce7-69b7-494c-8f2d-0b3afb18f20f.png)
> 

Getting Started

**Comment by zeref221** [comment]
Meet the teams

**Comment by zeref221** [comment]
Start and benefit

**Comment by zeref221** [comment]
Greet and g-meet

**Comment by zeref221** [comment]
Affairs to remember

**Comment by zeref221** [comment]
A Flair to Remember

**Comment by zeref221** [comment]
INITIALS AND ABBREVIATIONS

**Comment by zeref221** [comment]
The First step

**Comment by zeref221** [comment]
Mission Connect

**Comment by zeref221** [comment]
Club with benefits

**Comment by zeref221** [comment]
Kilometre high club!

**Comment by zeref221** [comment]
Club education

**Comment by zeref221** [comment]
C.L.U.B.S.

**Comment by zeref221** [comment]
MITBIO Alliance

**Comment by zeref221** [comment]
Attack on clubs

**Comment by zeref221** [comment]
Club chronicles

**Comment by zeref221** [comment]
Legend of the Clubs

**Comment by zeref221** [comment]
Game of Clubs (GOC)

**Comment by zeref221** [comment]
That time I got reincarnated in MITBio clubs

**Comment by zeref221** [comment]
Fresher's meet

**Comment by Shreeya-Kadam** [comment]
> Sample 14
> 
> ![Fresher's Event (1)](https://user-images.githubusercontent.com/68808399/133999255-d7e448e5-1b81-474e-9b0a-18d29fc39974.png)

@preetambala sir please review poster number 14. The team has finalized this one.

**Comment by vinita08** [comment]
![BEC TEAM VB (2)](https://user-images.githubusercontent.com/88326489/134127512-518a554a-9be0-4501-94ef-60c0db603b54.png)
@manaswiproject please check if this works

**Comment by zeref221** [comment]
@Bioengineering-Club-2021A/core-team @Bioengineering-Club-2021A/executive-team @preetambala 

Everyone please vote for one name for the 25th event
