### ISSUE TITLE
Holistic event 5: Poster competition 

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#25]

**Comment by manaswiproject** [comment]
Date: 27th Nov
Time: post-lunch (1:30pm)

Separate topics for FY-SY and TY
_Ask faculties for "problem statements"_

Slot wise presentation- 30 mins slots (x teams per slot)
Teams other than the ones given that slot won't be allowed inside 
Only supporters and teams allowed inside

Non-participants, will help with organisation

Submission of posters from 20-22nd
Faculty feedback by 24th

**Comment by manaswiproject** [comment]
**Deadlines:**
Topics form for faculty- PR team - 29th Oct (send)
Poster for event - Creative team - 31st Oct (ready)
PR message for event (with reg form)- PR team - 31st Oct (ready)

**Comment by manaswiproject** [comment]
Instruction file (send with message and poster): detailed instructions, rules about poster, template

**Comment by Amartya-18** [comment]
PR message for the faculty form: 

To ,
The esteemed faculty of MIT BIO (SBSR) 
Greetings for the day !!! 

From the New Normal , its time to say, we are back to normal . The word online , finally takes a halt as we are back on the field, & the  Bioengineering Club is ecstatic to organise /orchastrate  a poster competition ,that will provide an opportunity to decipher a new dimension of mind ,involving fusion of academic &holistic aspects ,which will indeed be an amazing experience. This poster competition will give students ,a chance to showcase their   research intensive approach ,creative& team management  skills .  So, we have the following mentioned topics for the competition....

So, please mark out the topics of your Interest , that will guide us to  opt for / finalize the topics for the competition.   We look forward to your expert guidance &  exuberant participation in this event.

**Comment by Sanyogita22** [comment]
https://forms.gle/onxLRcPxjCTBWuEP7
faculty form

**Comment by tanishqua27** [comment]
https://sprw.io/stt-caa987 , registration form

**Comment by nayanavarghese11** [comment]
![3](https://user-images.githubusercontent.com/68808399/139593217-71ebbe65-d36d-46de-a746-2c1e09c80962.png)
Poster sample 1. 
If the text part is looking crowded I can reduce the number of words or reduce the transparency. 
Open to suggestions.

**Comment by nayanavarghese11** [comment]
Poster Sample 2
![2](https://user-images.githubusercontent.com/68808399/139593348-958cf44f-4552-4161-a8ac-3be2de169fcc.png)

**Comment by nayanavarghese11** [comment]
Poster Sample 3
![4](https://user-images.githubusercontent.com/68808399/139593390-01da3dbd-46e4-416e-a80d-c463642dd371.png)

**Comment by nayanavarghese11** [comment]
Poster Sample 4

![5](https://user-images.githubusercontent.com/68808399/139593463-26d506ae-d79a-47e6-ab17-1f2f032f2018.png)

**Comment by nayanavarghese11** [comment]
Poster Sample 5

**Comment by nayanavarghese11** [comment]
Poster Sample 5

![1](https://user-images.githubusercontent.com/68808399/139593502-b21affc0-3fe8-4ef5-9c26-1c0367416679.png)
