### ISSUE TITLE
Social Mixer Ideas

### ISSUE THREAD

**Issue by zeref221** [Bioengineering-Club-2021A/Executive-Team#26]
Please drop your ideas down below!

Feel free to list any ideas for games, networking activities, or ice-breakers (Please include a brief description)

**Comment by shrabanagupta** [comment]
Do we find ideas for promoting bioengineering socially in an international platform so that it can benefit environment and human race?

**Comment by zeref221** [comment]
Sounds good on paper, but can you give an example to elaborate on this?

**Comment by shrabanagupta** [comment]
What I want to say is we as bioengineers work with various fields of biology and also engineering. So if we can come up with a topic or say something that is an application of Bioengineering as a domain which is also beneficial for the human race, then we will be able to connect with a lot more people who may have such common ideas in their minds as well. 
I don't have a clear idea as of now but can surely can work on it.

**Comment by zeref221** [comment]
Alright, even I'll think about it!
