### ISSUE TITLE
Create PR message for holistic event 1

### ISSUE THREAD

**Issue by manaswiproject** [Bioengineering-Club-2021A/Executive-Team#6]
Pls create PR message for event 1 and post here
Deadline- Thursday 12pm

**Comment by Anushka-CC-DS** [comment]
I have drafted a message, let me know if it needs any changes.

Good evening fellow Bioengineers,
We sincerely hope all of you are doing well and are safe!
This weekend, the Bioengineering Club is psyched to be hosting a holistic event filled with informative fun.
We have planned an interactive game of ‘Heads Up’ and encourage each and every one of you to participate and make this session a success!
Come join us this Saturday on August 14th at 5pm for the ultimate battle of wits and loads of fun!
We look forward to seeing you on Saturday!
